### ISSUE TITLE
Having some problems

### ISSUE THREAD

**Issue by JRioboo** [ameltech/sme-se868-a-library#6]
Hello, i'm using your library example and it says allways Locking GPS position, i don´t know how to fix the problem or where is it, could you help me? Thank you

**Comment by searobin** [comment]
Hi.
Please try to move outdoor in open air and retry the test.
It should work, if not please let me know.

Open air I mean outside of any building, without any high obstacle
in the neighborhood.

Ciao

Seve

**Comment by JRioboo** [comment]
Hi, thank you but it still the same way. I've tried with all versions avaliable, what could i do now? Maybe the GPS isn`t operating right?

**Comment by searobin** [comment]
If you take the latest version of board lib the Arrow one not the Ameltech and the latest version of gps lib, both downloaded through Arduino IDE it should work.

Otherwise you could check to download the Ameltech board lib and a previous gps version and retry.

Please do all tests in open sky.

To doublecheck, which is the Smarteverything version you are uising ?Fox, Fox3 or Lion?

Ciao

Severino

**Comment by JRioboo** [comment]
It works! With the first version the GPS is working now, thank you.

**Comment by aristay** [comment]
Hi! I'm using your library too.. and it works outdoor.. so, indoor SEgps is unavailable, isn't it?

**Comment by searobin** [comment]
Yes. 
The satellites signal can't be received indoor.
